name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.4'
          channel: 'stable'
      - run: flutter --version

  #    - name: Cache pub dependencies
  #      uses: actions/cache@v2
  #      with:
  #        path: ${{ env.FLUTTER_HOME }}/.pub_cache
  #        key: ${{ runner.os }}

      - name: Get flutter dependencies
        run: flutter pub get

#      - name: Run analyzer
#        run: flutter analyze
#
#      - name: Run tests
#        run: flutter test

      - name: Build Web App
        run: flutter build web

      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
    